name = "gleither"
description = "A small data-structure for representing an Either Monad"
docs_url = "https://hexdocs.pm/gleither/"
repo_url = "https://github.com/bwireman/gleither"
category = "Data Structures"
